services:
  # stacks-blockchain-api instance
  - name: byz1-mainnet-stx-blockchain-api
    type: pserv
    env: docker
    region: oregon
    plan: standard
    branch: master
    dockerfilePath: stacks-blockchain-api.Dockerfile
    dockerContext: .
    autoDeploy: false
    envVars:
      - key: PG_HOST
        fromDatabase:
          name: byz1-mainnet-postgres
          property: host
      - key: PG_PORT
        fromDatabase:
          name: byz1-mainnet-postgres
          property: port
      - key: PG_DATABASE
        fromDatabase:
          name: byz1-mainnet-postgres
          property: database
      - key: PG_USER
        fromDatabase:
          name: byz1-mainnet-postgres
          property: user
      - key: PG_PASSWORD
        fromDatabase:
          name: byz1-mainnet-postgres
          property: password
      - key: STACKS_CORE_EVENT_HOST
        value: 0.0.0.0
      - key: STACKS_BLOCKCHAIN_API_HOST
        value: 0.0.0.0
      - key: STACKS_BLOCKCHAIN_API_DB
        value: pg
      - key: STACKS_CORE_RPC_HOST
        fromService:
          name: byz1-mainnet-stx-blockchain
          type: pserv
          property: host
      - key: STACKS_CORE_RPC_PORT
        value: 80
      - fromGroup: byz1-mainnet-settings
    disk:
      name: api-event-replay
      mountPath: /root/stacks-blockchain/data
      sizeGB: 25

  # stacks-blockchain instance
  - name: byz1-mainnet-stx-blockchain
    type: pserv
    env: docker
    region: oregon
    plan: standard
    branch: master
    dockerfilePath: stacks-blockchain.Dockerfile
    dockerContext: .
    autoDeploy: false
    envVars:
      - key: STACKS_BLOCKCHAIN_API_HOST
        fromService:
          name: byz1-mainnet-stx-blockchain-api
          type: pserv
          property: host
      - fromGroup: byz1-mainnet-settings
    disk:
      name: byz1-mainnet-stx-blockchain
      mountPath: /root/stacks-blockchain/data
      sizeGB: 50

  # nginx proxy instance
  - name: byz1-mainnet-nginx
    type: web
    env: docker
    region: oregon
    plan: standard
    branch: master
    dockerfilePath: nginx.Dockerfile
    dockerContext: .
    healthCheckPath: /status
    autoDeploy: true
    envVars:
      - key: STACKS_BLOCKCHAIN_API_HOST
        fromService:
          name: byz1-mainnet-stx-blockchain-api
          type: pserv
          property: host
      - fromGroup: byz1-mainnet-settings

# Managed Postgres instance
databases:
  - name: byz1-mainnet-postgres
    plan: Standard Plus

envVarGroups:
  - name: byz1-mainnet-settings
    envVars:
      - key: NODE_ENV
        value: production
      - key: GIT_TAG
        value: master
      - key: STACKS_CHAIN_ID
        value: 0x00000001
      - key: V2_POX_MIN_AMOUNT_USTX
        value: 90000000260
      - key: STACKS_NETWORK
        value: mainnet
      - key: STACKS_EXPORT_EVENTS_FILE
        value: /root/stacks-blockchain/stacks-node-events.tsv
      - key: STACKS_CORE_EVENT_PORT
        value: 3700
      - key: STACKS_BLOCKCHAIN_API_PORT
        value: 3999
