services:
  # stacks-blockchain-api instance
  - name: managed-mainnet-stacks-blockchain
    type: web
    env: docker
    region: oregon
    plan: standard
    branch: master
    dockerfilePath: standalone.Dockerfile
    dockerContext: .
    healthCheckPath: /status
    autoDeploy: false 
    envVars:
      - key: PG_HOST
        fromDatabase:
          name: managed-mainnet-postgres
          property: host
      - key: PG_PORT
        fromDatabase:
          name: managed-mainnet-postgres
          property: port
      - key: PG_DATABASE
        fromDatabase:
          name: managed-mainnet-postgres
          property: database
      - key: PG_USER
        fromDatabase:
          name: managed-mainnet-postgres
          property: user
      - key: PG_PASSWORD
        fromDatabase:
          name: managed-mainnet-postgres
          property: password
      - key: STACKS_CORE_EVENT_PORT
        value: 3700
      - key: STACKS_CORE_EVENT_HOST
        value: 0.0.0.0
      - key: STACKS_BLOCKCHAIN_API_PORT
        value: 3999
      - key: STACKS_BLOCKCHAIN_API_HOST
        value: 0.0.0.0
      - key: STACKS_BLOCKCHAIN_API_DB
        value: pg
      - key: STACKS_CORE_RPC_HOST
        value: localhost
      - key: STACKS_CORE_RPC_PORT
        value: 20443
      - fromGroup: managed-mainnet-settings
    disk:
      name: stacks-blockchain-data
      mountPath: /root/stacks-blockchain/data
      sizeGB: 50 # optional

# # Managed postgres instance
databases:
  - name: managed-mainnet-postgres
    plan: standard

envVarGroups:
  - name: managed-mainnet-settings
    envVars:
      - key: NODE_ENV
        value: production
      - key: GIT_TAG
        value: master
      - key: STACKS_CHAIN_ID
        value: 0x00000001
      - key: V2_POX_MIN_AMOUNT_USTX
        value: 90000000260
      - key: STACKS_NETWORK
        value: mainnet
      - key: STACKS_EXPORT_EVENTS_FILE
        value: /root/stacks-blockchain/stacks-node-events.tsv

 